spring.application.name=SpringWebOne

spring.datasource.url=jdbc:mysql://localhost:3306/company_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ???????
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.kunkun.springwebone.entity
spring.profiles.active=dev
# auto change name field
mybatis.configuration.map-underscore-to-camel-case=true